export enum PropertyStatus {
  AVAILABLE = 'AVAILABLE',
  SOLD = 'SOLD',
  RENTED = 'RENTED',
  RESERVED = 'RESERVED',
  NOT_AVAILABLE = 'NOT_AVAILABLE',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  IN_MAINTENANCE = 'IN_MAINTENANCE',
  FORECLOSED = 'FORECLOSED'
}
