export enum PropertyType {
  SINGLE_FAMILY_HOME = 'SINGLE_FAMILY_HOME',
  COMMERCIAL = 'COMMERCIAL',
  APARTMENT = 'APARTMENT',
  TOWNHOUSE = 'TOWNHOUSE',
  CONDOMINIUM = 'CONDOMINIUM',
  MULTI_FAMILY_HOME = 'MULTI_FAMILY_HOME',
  VACANT_LAND = 'VACANT_LAND',
  INDUSTRIAL = 'INDUSTRIAL',
  OFFICE = 'OFFICE',
  RETAIL = 'RETAIL',
  WAREHOUSE = 'WAREHOUSE',
  HOSPITALITY = 'HOSPITALITY',
  MIXED_USE = 'MIXED_USE',
  AGRICULTURAL = 'AGRICULTURAL',
  SPECIAL_PURPOSE = 'SPECIAL_PURPOSE'
}
